# You can set any interface, that is listened by docker engine.
# e.g. docker_swarm_interface: "eth1"
docker_swarm_interface: "{{ ansible_default_ipv4['interface'] }}"
docker_swarm_addr: "{{ hostvars[inventory_hostname]['ansible_' + docker_swarm_interface]['ipv4']['address'] }}"
docker_swarm_port: 2377

docker_swarm_host_mask: "{{ docker_swarm_addr }}/{{ hostvars[inventory_hostname]['ansible_' + docker_swarm_interface]['ipv4']['netmask'] }}"
docker_swarm_network: "{{ docker_swarm_host_mask | ipaddr('host/prefix') }}"

# List of the users in the Docker group
docker_admin_users:
  - "{{ ansible_user | default(ansible_user_id) }}" # if ansible_user is not defined, we default to the ansible ansible_user_id fact

skip_engine: False # if true, skip the docker engine installation
skip_group: False  # if true, does not add the docker_admin_users to the docker_group_name
skip_swarm: False  # if true, skip the swarm setup
